from setuptools import setup
import setup_translate

pkg = 'Extensions.WebInterface'
setup(name='enigma2-plugin-extensions-webinterface',
       version='3.0',
       description='Control enigma2 with your Browser',
       package_dir={pkg: 'WebInterface'},
       packages=[pkg],
       package_data={pkg: ['images/*.png', '*.png', '*.xml', 'locale/*/LC_MESSAGES/*.mo', 'plugin.png', 'LICENSE', 'maintainer.info', 'm/bouquets.html.xml', 'm/epg.html.xml', 'm/index.html.xml', 'm/message.html.xml', 'm/movies.html.xml', 'm/power.html.xml', 'm/services.html.xml', 'm/timeraddbyeventid.html.xml', 'm/timers.html.xml', 'm/zap.html.xml', 'mobile/*.xml', 'web/*.xml', 'web-data/*.js', 'web-data/IEFixes.htc', 'web-data/PIE.htc', 'web-data/css/font-awesome.min.css', 'web-data/fonts/fonts.css', 'web-data/fonts/roboto-bold-webfont.eot', 'web-data/fonts/roboto-bold-webfont.svg', 'web-data/fonts/roboto-bold-webfont.ttf', 'web-data/fonts/roboto-bold-webfont.woff', 'web-data/fonts/roboto-regular-webfont.eot', 'web-data/fonts/roboto-regular-webfont.svg', 'web-data/fonts/roboto-regular-webfont.ttf', 'web-data/fonts/roboto-regular-webfont.woff', 'web-data/fonts/FontAwesome.otf', 'web-data/fonts/fontawesome-webfont.eot', 'web-data/fonts/fontawesome-webfont.svg', 'web-data/fonts/fontawesome-webfont.ttf', 'web-data/fonts/fontawesome-webfont.woff', 'web-data/fonts/fontawesome-webfont.woff2', 'web-data/gfx/*.png', 'web-data/gfx/*.gif', 'web-data/gfx/*.jpg', 'web-data/img/*.png', 'web-data/img/favicon.ico', 'web-data/lib/*.js', 'web-data/lib/datepicker/media/backstripes.gif', 'web-data/lib/datepicker/media/bg_header.jpg', 'web-data/lib/datepicker/media/bullet1.gif', 'web-data/lib/datepicker/media/bullet2.gif', 'web-data/lib/datepicker/media/cal.gif', 'web-data/lib/datepicker/media/cal-grey.gif', 'web-data/lib/datepicker/media/gradient-e5e5e5-ffffff.gif', 'web-data/lib/lang/*.js', 'web-data/m/css/jquery.mobile.structure-1.1.1.min.css', 'web-data/m/css/themes/dream.min.css', 'web-data/m/css/themes/images/ajax-loader.gif', 'web-data/m/css/themes/images/icons-18-black.png', 'web-data/m/css/themes/images/icons-18-white.png', 'web-data/m/css/themes/images/icons-36-black.png', 'web-data/m/css/themes/images/icons-36-white.png', 'web-data/m/script/jquery.mobile-1.1.1.min.js', 'web-data/tpl/default/default.appcache', 'web-data/tpl/default/index.html', 'web-data/tpl/default/multiepg.css', 'web-data/tpl/default/style.min.css', 'web-data/tpl/default/style_light.min.css', 'web-data/tpl/default/style_merlin_dark.min.css', 'web-data/tpl/default/style_modern.min.css', 'web-data/tpl/default/style.css', 'web-data/tpl/default/*.htm', 'web-data/tpl/default/streaminterface/*.htm', 'web-data/tpl/default/streaminterface/index.html', 'web-data/tpl/default/streaminterface/style.css']},
       cmdclass=setup_translate.cmdclass,  # for translation
      )
